on: [push, pull_request]

name: Clippy check

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        # Make sure CI fails on all warnings, including Clippy lints
        run: cargo clippy --all-targets --all-features -- -D warnings
